# 输入时隐藏鼠标指针
hide_cursor_when_typing yes

# 主题（保留你用的 dracula）
include dracula.conf

# 字体


font_family JetBrainsMonoNL Nerd Font Mono
bold_as_bright no
adjust_bold_font -1


font_size 18.7

# 窗口效果
background_opacity 1
background_blur 0

# 隐藏标题栏（只隐藏标题栏，保留极小边框）
hide_window_decorations titlebar-only


# 光标
enable_audio_bell no

# 关闭不提示
confirm_os_window_close 0
close_window_confirmation never

disable_ligatures never


notify_on_cmd_finish unfocused 10 notify
# 窗口失焦时，命令运行超过10秒完成后发通知

# Option 当作 Alt，使 Alt+数字 直达 tmux 的 M-数字
macos_option_as_alt yes
map alt+1 send_text all \x1b1
map alt+2 send_text all \x1b2
map alt+3 send_text all \x1b3
map alt+4 send_text all \x1b4
map alt+5 send_text all \x1b5
map alt+6 send_text all \x1b6
map alt+7 send_text all \x1b7
map alt+8 send_text all \x1b8
map alt+9 send_text all \x1b9
map cmd+1 send_text all \x1b1
map cmd+2 send_text all \x1b2
map cmd+3 send_text all \x1b3
map cmd+4 send_text all \x1b4
map cmd+5 send_text all \x1b5
map cmd+6 send_text all \x1b6
map cmd+7 send_text all \x1b7
map cmd+8 send_text all \x1b8
map cmd+9 send_text all \x1b9
